
version: "3"
networks:
  webnet:
   driver: bridge

services:
  postgres:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./client-management-service/postgres-scripts/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    ports:
      - "5432:5432"
  # app:
  #   build: ./client-management-service/
  #   environment:
  #     - PGUSER=telehealth
  #     - PGHOST=localhost
  #     - PGDATABASE=telehealth
  #     - PGPASSWORD=password
  #     - PGPORT=5432
  #     - PGSSL=false
  #     - LISTEN_PORT=3000
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - webnet