version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install lerna
          command: npm install -g lerna
      - run:
          name: Install Dependencies
          command: lerna bootstrap
      - run:
          name: Run tests
          command: lerna run build
workflows:
  react-build:
    jobs:
      - build
